### ISSUE TITLE
Python version in dependencies.json too specific

### ISSUE THREAD

**Issue by jeffyjefflabs** [nbgallery/ipydeps#11]
Dependencies are looked up using major-minor-micro python version.  It's unlikely that dependencies are actually different for a micro version change, so in practice we end up cut & pasting the entire list from e.g. 2.7.12 to 2.7.13.

It would be nice if you could list dependencies for python-2, python-2.7, and python-2.7.13 where more specific entries would override more general ones if there's a conflict.  That would enable the same level of detail we currently have but also remove the redundancy.

**Comment by billallen256** [comment]
Ok, looking at this again, it's not a huge code change.  Will spin up another branch soon to make sure it has the behavior you want.

**Comment by billallen256** [comment]
Ok, take a look at the version_dependencies branch.

**Comment by jeffyjefflabs** [comment]
Looks good to me!

**Comment by jeffyjefflabs** [comment]
Fixed by 6342313f164f83cd59ac8e54683f188b0e144fd0
