### ISSUE TITLE
ipydeps.pip fails based on order of installed packages

### ISSUE THREAD

**Issue by jgbradley1** [nbgallery/ipydeps#13]
When trying to install multiple packages, ipydeps will error out and not install _as many packages as possible_.

`ipydeps.pip(['urllib2', 'pandas'])`

will not install pandas while

`ipydeps.pip(['pandas', 'urllib2'])
`
will work. This side-case could be resolved by calling pip.main() on each individual package instead of all at once.

**Comment by billallen256** [comment]
To be totally honest, my first instinct was to just close this ticket, but it's more nuanced than that.

Python 3.5.2 with pip 9.0.1:
Both examples you provided generate an error and don't install anything, so the order doesn't matter in Python 3.

Python 2.7.12 with pip 9.0.1:
Both examples you provide generate an error, but the ['pandas','urllib2'] example installs pandas, _then_ generates an error for urllib2.

The real question though is how this list-passing feature is interpreted.  From our perspective, it's always been something that overrides some package installs (see dependencies.link in docs), then simply passes the remainder of the list to pip; pip then figures out the rest.  In other words, if you were to pass the same list to pip on the command line, then pip is going to error out.  In that case, the error is firmly outside the scope of ipydeps.

The alternative interpretation of this feature is that it's simply a convenience wrapper around a for-loop, with each iteration calling pip (or doing an override) for each package on the list.  The problem with this interpretation is that it requires the user to figure out the order that the packages need to be installed, which I would much prefer to avoid.

In my mind, it makes more sense to leave it up to pip to figure out the order of package installation.  Furthermore, if  this is only an issue with Python 2, then that definitely lowers its priority, as Python 2 is dying out.  However, I'd like to hear what other people think, so I'm going to leave this ticket open for a bit.  Sorry it took me so long to get around to responding.

**Comment by billallen256** [comment]
It's been about a year and I haven't heard any more input from people, so I'm closing this ticket.  We would probably need to re-run the tests anyway, as ipydeps and pip have changed a good bit in that time.
