### ISSUE TITLE
examine issues with pbr and pkg_resources

### ISSUE THREAD

**Issue by billallen256** [nbgallery/ipydeps#20]
Using pbr in `__init__.py` appears to generate another flavor of VersionConflict.

**Comment by billallen256** [comment]
@kafonek @jeffyjefflabs After looking at the docs and examples, I'm not convinced pbr is being used correctly in the offending code.  https://docs.openstack.org/pbr/latest/user/using.html

**Comment by billallen256** [comment]
This fix looks promising (and cleaner): https://github.com/nbgallery/ipydeps/compare/issue20

**Comment by billallen256** [comment]
Fixed in release 0.4.1: https://github.com/nbgallery/ipydeps/archive/0.4.1.tar.gz

**Comment by jeffyjefflabs** [comment]
I'm getting this error:

```
Collecting pkg_resources (from ipydeps)
  Could not find a version that satisfies the requirement pkg_resources (from ipydeps) (from versions: )
No matching distribution found for pkg_resources (from ipydeps)
```

Looks like pkg_resources is actually part of setuptools...?

**Comment by billallen256** [comment]
Hey look, it's 0.4.2: https://github.com/nbgallery/ipydeps/archive/0.4.2.tar.gz

Sorry about that.
