### ISSUE TITLE
Does not work with pip >= 10

### ISSUE THREAD

**Issue by leorochael** [nbgallery/ipydeps#28]
As of `pip` 10.0.0, all pip internal APIs have moved. This was announced [some time ago](
https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html)
 and was done on purpose to break uses of `pip` like an API, like `ipydeps` does:

```
In [4]: ipydeps.pip('numpy')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-90822e7d8c5f> in <module>()
----> 1 ipydeps.pip('numpy')

~/.virtualenvs/tmp-9001f5ea3da50232/lib/python3.6/site-packages/ipydeps/__init__.py in pip(pkg_name, verbose)
    340     packages = set(_pkg_name_list(pkg_name))
    341     orig_package_list_len = len(packages)
--> 342     packages = _subtract_installed(packages)
    343     overrides = _find_overrides(packages, _read_dependencies_link(_dependencies_link_location()))
    344 

~/.virtualenvs/tmp-9001f5ea3da50232/lib/python3.6/site-packages/ipydeps/__init__.py in _subtract_installed(packages)
    296 def _subtract_installed(packages):
    297     packages = set(( p.lower() for p in packages))  # removes duplicates
--> 298     installed = [ x.lower() for x in _already_installed() ]  # lowercase everything for comparison
    299     ret = set()
    300 

~/.virtualenvs/tmp-9001f5ea3da50232/lib/python3.6/site-packages/ipydeps/__init__.py in _already_installed()
    292 
    293 def _already_installed():
--> 294     return set([ pkg.project_name for pkg in _pip.get_installed_distributions() ])
    295 
    296 def _subtract_installed(packages):

AttributeError: module 'pip' has no attribute 'get_installed_distributions'
```

The fastest alternative I can think of is to use the `subprocess` module to call `pip` (or `python -m pip`) to install packages and only `pkg_resources` (or perhaps `pip freeze` as a subprocess) to query which packages are already installed.

**Comment by billallen256** [comment]
Please take a look at #15 to better understand why we did things the way we did.  I'm open to exploring the subprocess approach, but it looks like they just moved everything under _internal, so as long as we account for that, we should be able to continue doing what we're doing.  We've always been aware that this was unsupported and that we were not using pip "as intended," but it works.

Hopefully the subprocess approach will pan out, as it's theoretically cleaner.  My biggest concern is that the newly installed packages won't be immediately available for import without restarting the Python notebook kernel.  It would also help if pip wasn't vendoring in their own pkg_resources.

**Comment by leorochael** [comment]
I just read #15, and it seems to me it was a problem caused exactly by calling `pip` as a library instead of as a subprocess. Since pip keeps a vendored fork of `pkg_resources` from setuptools, it's state had to be refreshed along with the state from the standalone `pkg_resources`.

Moving pip invocation to a subprocess should help keep things simpler and the global state easier to manage. The `pkg_resources` library vendored by `pip` stops being a concern since it's state is encapsulated in the subprocess invocation, and goes away with it.
