### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by kylekyle** [nbgallery/ipydeps#3]
So we can build it into jg-ipython3.

**Comment by billallen256** [comment]
In the meantime, you should be able to install directly from github with:

`pip install http://github.com/jupyter-gallery/ipydeps/tarball/master#egg=package-1.0`

**Comment by kylekyle** [comment]
Oh! That works for now. Thanks!

**Comment by kylekyle** [comment]
I also had to add 

```
pip install http://github.com/jupyter-gallery/pypki2/tarball/master#egg=package-1.0
```

**Comment by kylekyle** [comment]
On alpine pip can't find pypki2 even though you have the dependency_links in setup.py. I have to install with the --no-deps flag and install pypki2 manually.

**Comment by billallen256** [comment]
Interesting.  What does `pip -V` return?  Also, do you have pip for Python 2 and pip for Python 3?  Usually there are alternative commands, like `pip2` and `pip3`.

**Comment by billallen256** [comment]
Now available at https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=ipydeps

Based on instructions from http://peterdowns.com/posts/first-time-with-pypi.html
