### ISSUE TITLE
Global config dir

### ISSUE THREAD

**Issue by jeffyjefflabs** [nbgallery/ipydeps#39]
Could ipydeps look for its configuration files in a global location (e.g. `/etc`) as well as `~/.config`?  We have a multi-user environment but would like to set the same dependencies.link for everyone.

**Comment by billallen256** [comment]
Done: https://github.com/nbgallery/ipydeps/blame/ae64d0c8550e2f69c17bb543df79b072822948e9/ipydeps/config.py#L27
