### ISSUE TITLE
Use ipylogging

### ISSUE THREAD

**Issue by billallen256** [nbgallery/ipydeps#46]
Logging features from ipydeps were pulled out into the ipylogging package.  Now ipydeps should use that.

**Comment by jaredbrower** [comment]
Would this include a way to set the logging level for ipydeps? I'm looking for a way to prevent ipydeps from printing to IPython.display.

**Comment by jaredbrower** [comment]
I made a local version of ipydeps to use ipylogging (minor change to __init__.py) and it now allows for changing the log level before running imports like the example below. Happy to share the code if necessary to get this issue resolved.

```
import logging
import ipydeps
logging.getLogger('ipydeps').setLevel(logging.WARNING)
ipydeps.pip('pandas')
```

**Comment by billallen256** [comment]
Done in https://github.com/nbgallery/ipydeps/blame/ae64d0c8550e2f69c17bb543df79b072822948e9/ipydeps/logger.py#L1
