### ISSUE TITLE
Improve README to not further promote exclamation point use in conjunction with install commands inside notebooks

### ISSUE THREAD

**Issue by fomightez** [nbgallery/ipydeps#49]
In the current README it presently states:

>"Unlike `!pip install`, ipydeps makes sure that the packages get installed into the same Python environment that's executing your notebook's code cells. No more `!pip`, `!pip3`, `!pip -V` frustrations for you and your users."

The magic install commands were added to IPython/Jupyter in 2019 so that for installation commands run inside IPython or a running `.ipynb` file, the installation occurs in the environment where the backing kernel is based. See [here](https://discourse.jupyter.org/t/why-users-can-install-modules-from-pip-but-not-from-conda/10722/4?u=fomightez) for more about that. The use of the magic versions of the install commands is the practice to encourage. The current wording in the README puts forth that the exclamation point in conjunction with install commands as something current and that only alternative. That is not the case and prominently featuring the anti-pattern of `!pip install` should be discouraged in favor of emphasizing the magic install commands that are current best practice. The magic `%pip install` even works in JupyterLite and has been adopted by Google Colab finally.

**Comment by billallen256** [comment]
Right you are, and coincidentally I was just correcting someone about the same thing yesterday.  Fixed in 40d1daf5caf62ff1815d4910778a84a8118a6caa.
