### ISSUE TITLE
Add self-updating

### ISSUE THREAD

**Issue by billallen256** [nbgallery/ipydeps#5]
This could probably just be a wrapper around `ipydeps.pip('ipydeps', upgrade=True)`.

**Comment by echowhisky** [comment]
Or could it also be an option in the ipydeps.conf file to have it always self update?

**Comment by billallen256** [comment]
Putting `--upgrade` in ipydeps.conf should do the trick, since ipydeps should just pick it up. #untested

**Comment by billallen256** [comment]
Given the need for underlying stability, making self-updates automatic now seems like a bad idea.  Power users should still be able to explicitly update though other means.  One day #4 will get rolled in, and then it will be slightly easier.
