### ISSUE TITLE
Does not find URL path options in pip freeze

### ISSUE THREAD

**Issue by blueninja416** [nbgallery/ipydeps#50]
Tested this on python3.11 with pip 24.0, and whenever a package had `<package> @ <url>` instead of `<package>==<version>`, ipydeps wouldn't find it when deciding whether to install packages again.

I found a solution to instead use `python3 -m pip list --format=freeze` instead of `pip freeze --all`, which *should* have the same functionality, but be more consistent, but being able to parse the `@ <url>` options would be another solution if the `pip list` command is too much of a change.

**Comment by billallen256** [comment]
Fixed in ae64d0c8550e2f69c17bb543df79b072822948e9 and released as version 2024.280.702.
