### ISSUE TITLE
Overrides vs dependencies

### ISSUE THREAD

**Issue by jeffyjefflabs** [nbgallery/ipydeps#7]
After executing override commands from the dependencies file, ipydeps should still pip install the module.  There are cases where those commands merely install a dependency (e.g. matplotlib requires freetype-dev) rather than a complete replacement for pip (e.g. the numpy apk).

Possibly this could be an option specified in the dependencies file, but it doesn't really hurt to do the pip install regardless -- if the override commands installed the actual package, you'll just get a message that it's already installed.

**Comment by billallen256** [comment]
I think I see what you're saying.  Not all overrides can be fulfilled by packages.  Sometimes a few packages need to be installed, then a pip command needs to be called.  It sounds like I need to add support for pip calls in the dependencies.json file so they can be listed in cases where there isn't a package.

**Comment by jeffyjefflabs** [comment]
Exactly.  I put a little patch into the docker image so it will just execute the _pip.main call even when there are overrides.  I thought about just adding the pip command into dependencies.json, but it's more complicated than that because you may not know additional options for the pip command (as when used with pypki2).

So, quick & dirty fix is to just remove the line that I commented out in the patch.  Better solution would be a way to specify in dependencies.json that you still need to run a pip command, but you'll need to add in the extra arguments from pypki2 or whatever else is configured.

**Comment by jeffyjefflabs** [comment]
Looking at your fix for #6 / #8 in bf9158ffb4d831ed3ed2904a7535b4801e59c8e7, a nice simple fix for this might be (in theory) to call `_subtract_installed` a second time after calling ` _run_overrides`.  That way, if the overrides were true overrides (e.g. installed the numpy apk), we'd subtract numpy out of the list and therefore would not try to install again via pip - but if the "overrides" merely installed dependencies, we would still proceed with the install via pip.

Unfortunately, it looks like `pip.get_installed_distributions()` doesn't update unless you restart the kernel, so we would need an alternate implementation for `_already_installed`.  A system call to `pip list` would work but is kinda hacky - is there another way?

**Comment by billallen256** [comment]
Calling `_subtract_installed()` again after the overrides makes sense.

`pip list` just calls `pip.get_installed_distributions()`:
https://github.com/pypa/pip/blob/master/pip/commands/list.py

Is it working there because it's happening in a separate process?

**Comment by jeffyjefflabs** [comment]
That was my guess.  I didn't poke around long enough to see if there was a way to force a refresh.  I was just testing in the python shell by calling `pip.get_installed_distributions()` before and after doing `os.system("pip install requests")`, so that may not have been the perfect test.
