### ISSUE TITLE
Don't install dependencies.json files when the package is already installed

### ISSUE THREAD

**Issue by somedave** [nbgallery/ipydeps#8]
I think we're noticing that once you install a package one, if you `ipydeps.pip('<package>')` again it will wait while it installs any dependencies associated with the package in the `dependencies.json` file even though that package (and its corresponding dependencies) was already installed.

Is there a way to test to see if the package is installed before any related dependencies in dependencies.json are installed?

**Comment by billallen256** [comment]
I think I have the fix scribbled down somewhere at the office.  I'll try to remember to bring it home and add it in this week.

**Comment by billallen256** [comment]
Ok, the fix has been added.  If no one spots any issues this week, I'll close this ticket.

**Comment by jeffyjefflabs** [comment]
I think this is resolved.
