### ISSUE TITLE
Print a message after pip() completion when running in Jupyter

### ISSUE THREAD

**Issue by jeffyjefflabs** [nbgallery/ipydeps#9]
When using ipydeps in Jupyter, it would be nice to print a message when `ipydeps.pip()` commands are finished, similar to what mypki does for Ruby.  After the fix for #6 and #8, if a package is already installed such that the `pip()` call is a no-op, then the code completes without any output.  The user might wonder if anything actually happened, especially since the `pip()` call now completes very quickly.  Of course, nothing did happen, but a simple "Package foo [successfully|already] installed" message would probably be comforting to the novice user.

There are already some good logger messages in the code -- it might suffice to automatically configure a stdout logger when ipython is detected.

**Comment by billallen256** [comment]
The new messaging in version 0.7.0 prints out what packages were installed then prints "Done" at the end.
